// <auto-generated />
using System;
using BusTicketReservationSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BusTicketReservationSystem.Infrastructure.Migrations
{
    [DbContext(typeof(BusTicketDbContext))]
    partial class BusTicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusTicketReservationSystem.Domain.Entities.Bus", b =>
                {
                    b.Property<Guid>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer");

                    b.HasKey("BusId");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            BusId = new Guid("20000000-0000-0000-0000-000000000001"),
                            BusName = "99 DHA-CHA",
                            BusType = "Non AC",
                            CompanyName = "National Travels",
                            TotalSeats = 40
                        },
                        new
                        {
                            BusId = new Guid("20000000-0000-0000-0000-000000000002"),
                            BusName = "68 RAJ CHAPA",
                            BusType = "Non AC",
                            CompanyName = "Hanif Enterprise",
                            TotalSeats = 40
                        });
                });

            modelBuilder.Entity("BusTicketReservationSystem.Domain.Entities.BusSchedule", b =>
                {
                    b.Property<Guid>("BusScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JourneyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("BusScheduleId");

                    b.HasIndex("BusId");

                    b.HasIndex("RouteId");

                    b.ToTable("BusSchedules");

                    b.HasData(
                        new
                        {
                            BusScheduleId = new Guid("30000000-0000-0000-0000-000000000001"),
                            BusId = new Guid("20000000-0000-0000-0000-000000000001"),
                            JourneyDate = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            RouteId = new Guid("10000000-0000-0000-0000-000000000001"),
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            BusScheduleId = new Guid("30000000-0000-0000-0000-000000000002"),
                            BusId = new Guid("20000000-0000-0000-0000-000000000002"),
                            JourneyDate = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            RouteId = new Guid("10000000-0000-0000-0000-000000000001"),
                            StartTime = new TimeSpan(0, 7, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("BusTicketReservationSystem.Domain.Entities.Route", b =>
                {
                    b.Property<Guid>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RouteId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Destination = "Rajshahi",
                            Origin = "Dhaka"
                        });
                });

            modelBuilder.Entity("BusTicketReservationSystem.Domain.Entities.BusSchedule", b =>
                {
                    b.HasOne("BusTicketReservationSystem.Domain.Entities.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusTicketReservationSystem.Domain.Entities.Route", "Route")
                        .WithMany("BusSchedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("BusTicketReservationSystem.Domain.Entities.Route", b =>
                {
                    b.Navigation("BusSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
